const MyDefaultTheme = {
  dark: false,
  colors: {
    background: '#fcfcfc',
    background2: '#eff3f4',
    border: '#858585',
    button: '#3454fc',
    card: '#ffffff',
    cardSeconday: '#eff3f4',
    notification: '#ff3b30',
    primary: '#007aff',
    secondary: '#E7EAF6',
    text: '#393E46',
    textInput: '#E8EDF1',
    textInputBorder: '#878DBB',
    surface: 'black',
    accent: 'black',
    icon: 'black',
    onSurface: 'black',
    disabled: 'black',
    placeholder: 'black',
    backdrop: 'black',
    shadow: 'grey',
  },
};

const MyDarkTheme = {
  dark: true,
  colors: {
    background: '#000000',
    background2: '#080808',
    border: '#ffffff',
    button: '#3454fc',
    card: '#18161C',
    cardSeconday: '#303337',
    notification: '#ff453a',
    primary: '#0a84ff',
    secondary: '#242424',
    text: 'white',
    textInput: '#23252D',
    textInputBorder: '#878DBB',
    surface: '#454f57',
    accent: '#e5e5e7',
    icon: 'white',
    onSurface: 'black',
    disabled: 'black',
    placeholder: 'white',
    backdrop: 'black',
    shadow: 'white',
  },
};
export { MyDarkTheme, MyDefaultTheme };
